# Generated by Django 4.0.1 on 2022-03-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('website', models.URLField(max_length=120)),
                ('comentario', models.TextField()),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products Dell'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services Dell'},
        ),
    ]
