# Generated by Django 4.0.1 on 2022-03-23 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdell', '0003_comentarios_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
